# Generated by Django 5.2 on 2025-04-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_order_number_client_alter_order_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='ORD-2025-dqfnvu', editable=False, max_length=15, unique=True),
        ),
    ]
