# Generated by Django 5.2 on 2025-04-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_order_number_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='ORD-2025-1ru027', editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='products'),
        ),
    ]
