# Generated by Django 5.2 on 2025-05-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_date_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default='ORD-2025-24alaa', editable=False, max_length=15, null=True, unique=True),
        ),
    ]
