# Generated by Django 5.2 on 2025-05-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_commune_order_company_order_wilaya_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default='ORD-2025-wdpdox', editable=False, max_length=15, null=True, unique=True),
        ),
    ]
