# Generated by Django 5.2 on 2025-05-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default='ORD-2025-20250524211949374052-ujd2', editable=False, max_length=15, null=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.product'),
            preserve_default=False,
        ),
    ]
